version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=sql-server
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=YourStrong@Password123
      - DB_NAME=master
    depends_on:
      - sql-server

volumes:
  sql-data: